version: '3'
services:
  budgeting:
    image: budgeting:latest
    restart: unless-stopped
    ports:
      - '4200:3000'
    volumes:
      - budgeting_data:/usr/src/private
    environment:
      - HTTPS=true
      - HOST=0.0.0.0
      - PORT=9090
      - HTTPS_CRT=/etc/ssl/private/budgeting.crt
      - HTTPS_key=/etc/ssl/private/budgeting.key
      - REPOSITORY_PATH=/usr/src/private/

volumes:
  budgeting_data:
