version: '3'
services:
  budgeting:
    image: budgeting:latest
    restart: unless-stopped
    ports:
      - '4200:3000'
    volumes:
      - budgeting_data:/usr/src/private
    environment:
      - HOST=0.0.0.0
      - REPOSITORY_PATH=/usr/src/private/

volumes:
  budgeting_data: